server {
    listen 80;
    server_name stock.numeriquesolution.com;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Angular SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers Spring Boot (les endpoints commencent par /api)
    location /api/ {
        proxy_pass http://stock_backend:8080;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Cache des assets statiques
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
