spring.profiles.active=dev
#spring.profiles.active=dev
# ==================== JWT ====================
app.jwt.secret=change-me-in-production-please-use-a-very-long-secret-key-at-least-256-bits-required-for-hs256-algorithm
app.jwt.expiration-ms=900000

# ==================== CORS ====================
app.cors.allowed-origins=http://localhost:4200,http://localhost:3000,http://localhost:8080
 debut de refractoration
app.jwt.refresh-expiration-ms=604800000
